"""The GitHub Pages record (docs/): results per generation and a short report on each, rebuilt from runs/.

    python -m kev_tetris.site            # write docs/data.js
    python -m kev_tetris.site --push     # ... and commit that file alone and push it

docs/index.html reads window.KEV_DATA from docs/data.js. The stream server calls publish() whenever a generation is
registered, so the page follows the training without anyone touching it.
"""
from __future__ import annotations

import json, subprocess, sys, time
from pathlib import Path

from . import generations, replays
from .tetris import Game

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "data.js"
CACHE = ROOT / "runs" / "site_cache.json"   # per-generation figures recounted from the recordings
LOG = ROOT / "runs" / "site.log"


def _recount(gen: int) -> dict:
    """Replay the test games: Tetrises, survivors and the longest game (older generations did not record these)."""
    games = replays.load(gen)
    if not games: return {}
    tetrises = score = lines = 0
    for r in games:
        game, pol = Game(seed=r["seed"]), replays.ReplayPolicy(r)
        while not game.over and game.pieces < len(r["moves"]): game.step(pol.decide(game).placement)
        tetrises += game.tetrises; score += game.score; lines += game.lines
    return {"tetris": round(tetrises / len(games), 2), "spl": round(score / max(1, lines), 1),
            "survived": sum(1 for r in games if not r["died"]), "games": len(games),
            "best_pieces": max(r["pieces"] for r in games)}


def _report(g: dict, parent: dict | None) -> str:
    """A few plain sentences on one generation, compared with its parent."""
    lineage = "学習前" if g["reward"] == "-" else f"報酬 {g['reward']}、親は第{g['parent']}世代"
    s = [f"第{g['gen']}世代({lineage})。平均得点 {g['score']:,.0f}、平均 {g['pieces']:.0f} 手(最大 {g['best_pieces']} 手、"
         f"500手到達 {g['survived']}/{g['games']})、テトリス {g['tetris']:.1f} 回/ゲーム、1ラインあたり {g['spl']:.1f} 点。"]
    if parent:
        d = g["score"] - parent["score"]
        s.append(f"親の第{parent['gen']}世代と比べて、平均得点は {'+' if d >= 0 else ''}{d:,.0f}。")
        notes = []
        if g["pieces"] < parent["pieces"] * 0.8: notes.append("生き残る手数が大きく減った")
        elif g["pieces"] > parent["pieces"] * 1.2: notes.append("生き残る手数が大きく伸びた")
        if g["tetris"] >= parent["tetris"] + 0.5: notes.append("テトリスが増えた")
        elif g["tetris"] + 0.5 <= parent["tetris"]: notes.append("テトリスが減った")
        if g["spl"] >= parent["spl"] + 3: notes.append("1ラインあたりの得点が上がった(消し方がうまくなった)")
        elif g["spl"] + 3 <= parent["spl"]: notes.append("1ラインあたりの得点が下がった")
        if notes: s.append("、".join(notes) + "。")
    return "".join(s)


def build() -> dict:
    try: cache = json.loads(CACHE.read_text(encoding="utf-8"))
    except (OSError, ValueError): cache = {}
    rows = []
    for e in generations.load():
        ev, key = e.get("eval") or {}, str(e["gen"])
        if key not in cache: cache[key] = _recount(e["gen"])
        c = cache[key]
        rows.append({"gen": e["gen"], "reward": "-" if e["gen"] == 0 else e.get("reward", "v1"), "parent": e.get("parent"),
                     "score": ev.get("mean_score"), "best_score": ev.get("best_score"), "lines": ev.get("mean_lines"),
                     "pieces": ev.get("mean_pieces"), "best_pieces": c.get("best_pieces"), "survived": c.get("survived", 0),
                     "games": c.get("games", ev.get("games", 5)), "spl": c.get("spl", 0.0), "tetris": c.get("tetris", 0.0),
                     "min": (e.get("train") or {}).get("minutes"), "created": e.get("created")})
    by_gen = {r["gen"]: r for r in rows}
    for r in rows: r["report"] = _report(r, by_gen.get(r["parent"]))
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(cache), encoding="utf-8")
    try: status = json.loads((ROOT / "runs" / "rl_status.json").read_text(encoding="utf-8"))
    except (OSError, ValueError): status = {}
    return {"updated": time.strftime("%Y-%m-%d %H:%M"), "gens": rows,
            "training": {"gen": status.get("gen"), "state": status.get("state")}}


def write() -> bool:
    """-> whether docs/data.js changed."""
    text = "// generated by kev_tetris.site from runs/; do not edit\nwindow.KEV_DATA = " + \
           json.dumps(build(), ensure_ascii=False, indent=1) + ";\n"
    old = DATA.read_text(encoding="utf-8") if DATA.exists() else ""
    # the timestamp alone changing is not news
    strip = lambda t: "\n".join(l for l in t.splitlines() if '"updated"' not in l)
    if strip(old) == strip(text): return False
    DATA.write_text(text, encoding="utf-8")
    return True


def publish(push: bool = True) -> str:
    """Rebuild docs/data.js and, if it changed, commit that file only and push it. Never raises: the caller is the
    live stream server."""
    try:
        if not write(): return "unchanged"
        if not push: return "written"
        latest = max((g["gen"] for g in generations.load()), default=0)
        git = lambda *a: subprocess.run(["git", *a], cwd=ROOT, capture_output=True, text=True, timeout=300)
        git("add", "docs/data.js")
        r = git("commit", "-m", f"Update results: generation {latest}", "--", "docs/data.js")
        if r.returncode and "nothing to commit" not in r.stdout: return f"commit failed: {r.stderr.strip()[:300]}"
        r = git("push", "origin", "HEAD:main")
        return "pushed" if r.returncode == 0 else f"push failed: {r.stderr.strip()[:300]}"
    except Exception as e:   # noqa: BLE001
        return f"error: {e}"


def log(msg: str):
    try:
        with LOG.open("a", encoding="utf-8") as f: f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} {msg}\n")
    except OSError:
        pass


if __name__ == "__main__":
    result = publish(push="--push" in sys.argv)
    log(f"manual: {result}")
    print(result)
